# --- Input files ---
base_path: "data/0.045Cpsqm_neg/20_"
runs:
  - "A"
  #- "B"
  #- "C"

files:
  trajectory: "process_0.045Cpsqm_neg_1.0M_KCl_20.lammpstrj"
  velocity: "process_0.045Cpsqm_neg_1.0M_KCl_20_vel.lammpstrj"
  force: "process_0.045Cpsqm_neg_1.0M_KCl_20_f.lammpstrj"
  stress: "process_0.045Cpsqm_neg_1.0M_KCl_20_stress_therm.lammpstrj"
  data: "data/data_files/0.045Cpsqm_neg_1.0M_KCl.dat"
  thermo_directory: "data/"
  thermo: "20_neg.txt"

# --- Atom types ---
atom_types:
  oxygen: 2
  hydrogen: 3
  potassium: 4
  chloride: 5

# --- Timestep size and FD scheme ---
dt: 0.5
finite_difference_scheme: "central difference"

# --- Analysis parameters ---
region:
  zlo: 0.0
  zhi: 7.5

density:
  bin_size: 0.1
  zlo: -5.0
  zhi: 20.0

velocity_distribution:
  zlo: 40.0
  zhi: 60.0
  component: 0
  bins: 50

# --- Output ---
output:
  base_folder: "results/"
  prefix: "20_neg_"
