# --- Input files ---
base_path: "data/0.045Cpsqm_neg/20_"
runs:
  - "A"
  - "B"
  - "C"

files:
  trajectory: "relax_0.045Cpsqm_neg_1.0M_KCl_20.lammpstrj"
  velocity: "relax_0.045Cpsqm_neg_1.0M_KCl_20_vel.lammpstrj"
  force: "relax_0.045Cpsqm_neg_1.0M_KCl_20_f.lammpstrj"
  stress: "relax_0.045Cpsqm_neg_1.0M_KCl_20_stress_therm.lammpstrj"
  data: "data/data_files/0.045Cpsqm_neg_1.0M_KCl.dat"
  thermo_directory: "data/"
  thermo: "20_neg.txt"

# --- Atom types ---
atom_types:
  oxygen: 2
  hydrogen: 3
  potassium: 4
  chloride: 5

# --- Timestep size and FD scheme ---
dt: 200.0
finite_difference_scheme: "central difference"

# --- Analysis parameters ---
region:
  zlo: 0.0
  zhi: 7.5

density:
  bin_size: 0.1
  zlo: -5.0
  zhi: 20.0

velocity_distribution:
  zlo: 40.0
  zhi: 60.0
  component: 0
  bins: 50

plotting_options:
  water_density_xlo: -2.0
  water_density_xhi: 2.0
  water_density_ylo: 0.016
  water_density_yhi: 0.026

  potassium_density_xlo: -2.0
  potassium_density_xhi: 2.0
  potassium_density_ylo: 5E-5
  potassium_density_yhi: 4E-4

  chloride_density_xlo: -2.0
  chloride_density_xhi: 2.0
  chloride_density_ylo: 5E-5
  chloride_density_yhi: 4E-4

  xx_stress_xlo: -2.0
  xx_stress_xhi: 2.0
  xx_stress_ylo: -1.4E6
  xx_stress_yhi: -0.5E6

  yy_stress_xlo: -2.0
  yy_stress_xhi: 2.0
  yy_stress_ylo: -1.4E6
  yy_stress_yhi: -0.5E6

  zz_stress_xlo: -2.0
  zz_stress_xhi: 2.0
  zz_stress_ylo: -0.8E6
  zz_stress_yhi: 2E6

# --- Output ---
output:
  base_folder: "results/"
  prefix: "relax_20_neg_7.5Ang"
