# --- Input files ---
base_path: "data/0Cpsqm/140_"
runs:
  - "A"
  - "B"
  - "C"
  - "D"

files:
  trajectory: "process_0Cpsqm_1.0M_KCl_140.lammpstrj"
  velocity: "process_0Cpsqm_1.0M_KCl_140_vel.lammpstrj"
  force: "process_0Cpsqm_1.0M_KCl_140_f.lammpstrj"
  stress: "process_0Cpsqm_1.0M_KCl_140_stress_therm.lammpstrj"
  data: "data/data_files/0Cpsqm_1.0M_KCl.dat"
  thermo_directory: "data/"
  thermo: "140_0.txt"

trajectory_type: "process"

# --- thermodynamic output reading parameters ---
thermo_process_ID: 2

# --- Atom types ---
atom_types:
  carbon: 1
  oxygen: 2
  hydrogen: 3
  potassium: 4
  chloride: 5

# --- Timestep size and FD scheme ---
dt: 1.0
finite_difference_scheme: "central difference"

# --- Analysis parameters ---
region:
  zlo: 0.0
  zhi: 7.5

density:
  bin_size: 0.1
  zlo: -5.0
  zhi: 20.0

velocity_distribution:
  zlo: 40.0
  zhi: 60.0
  component: 0
  bins: 50

carbon_positions:
  zlo: 5.0

transient_density_profile:
  zlo: -5.0
  zhi: 20.0
  bin_width: 0.1

plotting_options:
  water_density:
    time_series:
      smoothing_factor: 2.0
      spline_order: 4
    hysteresis:
      xlo: -2.0
      xhi: 2.0
      ylo: 0.016
      yhi: 0.026
  potassium_density:
    time_series:
      smoothing_factor: 2.0
      spline_order: 4
    hysteresis:
      xlo: -2.0
      xhi: 2.0
      ylo: 0.00005
      yhi: 0.0004
  chloride_density:
    time_series:
      smoothing_factor: 2.0
      spline_order: 4
    hysteresis:
      xlo: -2.0
      xhi: 2.0
      ylo: 0.00005
      yhi: 0.0004
  ionic_charge_density:
    time_series:
      smoothing_factor: 2.0
      spline_order: 4
    hysteresis:
      xlo: -2.0
      xhi: 2.0
      ylo: -0.0004
      yhi: 0.0004
  oxygen_xx_stress:
    time_series:
      smoothing_factor: 2.0
      spline_order: 4
    hysteresis:
      xlo: -2.0
      xhi: 2.0
      ylo: -1400000
      yhi: -500000
  oxygen_yy_stress:
    time_series:
      smoothing_factor: 2.0
      spline_order: 4
    hysteresis:
      xlo: -2.0
      xhi: 2.0
      ylo: -1400000
      yhi: -500000
  oxygen_zz_stress:
    time_series:
      smoothing_factor: 2.0
      spline_order: 4
    hysteresis:
      xlo: -2.0
      xhi: 2.0
      ylo: -800000
      yhi: 2000000
  interfacial_temperature:
    time_series:
      smoothing_factor: 2.0
      spline_order: 4
    hysteresis:
      xlo: -2.0
      xhi: 2.0
      ylo: 240
      yhi: 400

equilibrium_benchmark_prefix: "equil_globalnvt_frozen_0_7.5Ang"

# --- Output ---
output:
  base_folder: "results/"
  prefix: "process_140_0_7.5Ang"
